const { create, fetchAll, fetch, update, delete: deleteClub, fetchAllActive, fetchPlayers } = require('../controllers/Club');
const router = require('express').Router();
router.post('/', create);
router.get('/', fetchAll);
router.get('/active', fetchAllActive);
router.get('/:id', fetch);
router.put('/:id', update);
router.delete('/:id', deleteClub);
router.get('/:id/players', fetchPlayers);
module.exports = router;